### PR TITLE
removed invite edit or smth

### PR DESCRIPTION
**Pull request by no-u101**
checks if the edited message has a invite in it probably needs work also fixed a spelling error because im bored

### CODE REVIEW

**Review by megamaz — CHANGES_REQUESTED** [review]
Please create a method instead of copy-pasting code. It makes the code cleaner and more usable in case it needs fixing.

**Comment by no-u101** [comment]
.

**Comment by no-u101** [comment]
.

**Review by megamaz — CHANGES_REQUESTED** [review]
I requested that you make a function to house the check for admin.

**Review by megamaz — CHANGES_REQUESTED** [review]
no

**Comment by no-u101** [comment]
bullying mega part 1

**Comment by megamaz** [comment]
Still could be optimized but I'll make those edits myself.

**Comment by megamaz** [comment]
Try to check that the code actually runs before making a pr next time please?

**Pull request merged**
